language: node_js
node_js:
- "8.11.3"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
- export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true

stages:
  - test

jobs:
  include:
    - stage: test
      script: yarn run lint
    -
      script: yarn test
