language: node_js
node_js:
- 8.11.3
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
- export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
stages:
- test
- name: deploy
  if: tag IS present

jobs:
  include:
  - stage: test
    script: yarn run lint
    name: "linting"
  - script: yarn test
    name: "testing"
  - stage: deploy
    name: "Deploy to production"
    script: yarn build:all
    deploy:
      app: wind4fun-web
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: fu5NcasldjwwG+7/QMvuBfq6kHBEizHrIHTWx+G6tNnIRpTj2CLoO9U/vJMIYS0nhwwX4diwSewrsj3kaKmN5KpfKFALOD4N3Khuhh61okgyd5cNpHWhJYb0OZWChSLtD+FwID0ehKQf1vVNBEgIAGUHaaOYQbmPQkKzyz6Hi28xOXZE45uLKekjtkfZOIfWWF+PJGfUsEddlQROlVKwFAJk5EzqArppXbshXnEFxbtuuEbT5G79VYn8SKWLtcDs8sOcuHpyM1+dLcsHNGvf0/eAJbbwVm47o34TcYcmKtRclIIjsWTRA6fsetktPb3ZVW1lcP73L13JHoPEzgvDhpasWmMIXCJbwSvLTmdEorCHPvkd6Ct0YmjUQqlkgzkCQfmq7h46C6TVIel5WMJLBWzpPliu+cPwWJ9sBUoeidG6qF4Irw/YmB3Ao9IWJCnsn+lrmU/jDlFtuwyYh1nTb8ewJG3azY62tKrn1dIQPhMEee/i7WL9rVxcbstN2FJOS1GhLsGrKifVUT/3i9iOnsHRq1pT5GbiN0lzgUE0X32kWZmEsy5NV4JXQq3mmGhnix7RTj/MENX2Kq5BGNd1iPGhPcknmSmKavbARg8f3tkXdL6r9N+H710dxp0xOQJIS/ET2U2wLo09Bmuvpeqv3xevdLsAlGWkAOmxhaQVOiU=
      on:
        repo: dracomithril/wind4fun-web
        tags: true
