export const ADD_NEW_EMPLOYEE = 'ADD_NEW_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const ADD_NEW_BOARD = 'ADD_NEW_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';
export const LOGIN_USER = 'LOGIN_USER';
